version: '3.8'

services:
  frontend:
    image: example-frontend
    ports:
      - 5000:5000
    container_name: example-frontend

  backend:
    image: example-backend
    ports:
      - 8080:8080
    environment:
      - REDIS_HOST=redis
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DATABASE=postgres
    depends_on:
      - redis
      - postgres
    container_name: example-backend
    volumes:
      - ./database:/var/lib/postgresql/data
    
  redis:
    image: redis
    container_name: example-redis
  
  postgres:
    image: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./database:/var/lib/postgresql/data
      
  nginx:
    image: example-nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf    
    ports:
      - 80:80 # Changed 8080:80 to 80:80 as 8080 was already allocated
    container_name: example-nginx
    depends_on:
      - frontend
      - backend
