version: '3.8'

services:
  frontend:
    image: example-frontend
    ports:
      - 5000:5000
    container_name: example-frontend

  backend:
    image: example-backend
    ports:
      - 8080:8080
    environment:
      - REDIS_HOST=redis
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DATABASE=postgres
    depends_on:
      - redis
      - postgres
    container_name: example-backend
    
  redis:
    image: redis
    container_name: example-redis
  
  postgres:
    image: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=postgres
