version: '3.8'

services:
  frontend:
    image: example-frontend
    ports:
      - 5000:5000
    container_name: example-frontend

  backend:
    image: example-backend
    ports:
      - 8080:8080
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis  
    container_name: example-backend
    
  redis:
    image: redis
    container_name: example-redis
    
